import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/prisma';
import { getSession } from '@/lib/session';
import { GoogleGenerativeAI } from '@google/generative-ai';

const genAI = new GoogleGenerativeAI(process.env.GOOGLE_API_KEY || '');

export async function POST(req: NextRequest, { params }: { params: Promise<{ bookId: string }> }) {
  try {
    const session = await getSession();
    if (!session?.userId) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { bookId } = await params;

    // 1. Fetch Book & User Profile
    const user = await prisma.user.findUnique({
      where: { id: session.userId },
      include: { profile: true },
    });

    if (!user?.profile) {
      return NextResponse.json({ error: 'User profile not found' }, { status: 404 });
    }

    const COST = 10; // Cost for generating a full draft
    if (user.profile.credits < COST) {
      return NextResponse.json({ error: 'Insufficient credits' }, { status: 403 });
    }

    const book = await prisma.book.findUnique({
      where: { id: bookId, userId: session.userId },
      include: { characters: true, worldBible: true },
    });

    if (!book) {
      return NextResponse.json({ error: 'Book not found' }, { status: 404 });
    }

    // 2. Construct Prompt
    const model = genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });

    const charContext = book.characters.map((c) => `${c.name} (${c.role}): ${c.description}`).join('\n');
    const worldContext = book.worldBible.map((w) => `${w.name} (${w.category}): ${w.description}`).join('\n');

    const prompt = `
      You are a professional fiction author. Write the FIRST CHAPTER for the following book.
      
      BOOK DETAILS:
      Title: ${book.title}
      Genre: ${book.genre}
      Tone: ${book.tone}
      Story Arc: ${book.storyArc}
      
      CHARACTERS:
      ${charContext}
      
      WORLD/SETTING:
      ${worldContext}
      
      INSTRUCTIONS:
      - Write a compelling opening chapter (approx. 1000-1500 words).
      - Establish the setting and introduce the protagonist.
      - Hook the reader immediately.
      - Use the provided characters and world details.
      - Format with markdown (use # for title, ## for scenes).
      
      START WRITING:
    `;

    console.log('--- GENERATE DRAFT PROMPT ---', prompt);

    // 3. Call AI
    const result = await model.generateContent(prompt);
    const draftContent = result.response.text();

    if (!draftContent) {
      throw new Error('AI returned empty content');
    }

    // 4. Save Chapter & Deduct Credits
    const [newChapter, updatedProfile] = await prisma.$transaction([
      prisma.chapter.create({
        data: {
          bookId: book.id,
          title: 'Chapter 1: The Beginning',
          content: draftContent,
          order: 1,
          summary: 'The opening chapter generated by AI.',
          targetWordCount: 1500,
        },
      }),
      prisma.profile.update({
        where: { userId: session.userId },
        data: { credits: { decrement: COST } },
      }),
    ]);

    return NextResponse.json({
      success: true,
      chapter: newChapter,
      credits: updatedProfile.credits,
    });
  } catch (error: any) {
    console.error('Error generating draft:', error);
    return NextResponse.json({ error: 'Failed to generate draft', details: error.message }, { status: 500 });
  }
}
